-- Full-text search support for news_articles.
--
-- Hand-written rather than generated by Prisma, because Prisma cannot express
-- generated columns, weighted tsvectors, GIN indexes or pg_trgm.
--
-- Design notes:
--  * A STORED generated column, not an expression index: the vector is computed once
--    on write (ingestion) instead of on every query, and `ts_rank` can read it directly.
--  * Weights encode editorial importance: a term in the headline (A) outranks the same
--    term in the description (B) or body (C). Without this, a passing mention in a long
--    article outranks a headline match.
--  * `to_tsvector('english', ...)` with an explicit regconfig is IMMUTABLE, which is
--    what makes a generated column legal here.

-- Trigram matching, used as the fallback for typos and partial words where
-- full-text search finds nothing.
CREATE EXTENSION IF NOT EXISTS pg_trgm;

ALTER TABLE "news_articles"
  ADD COLUMN "search_vector" tsvector
  GENERATED ALWAYS AS (
    setweight(to_tsvector('english', coalesce("title", '')), 'A') ||
    setweight(to_tsvector('english', coalesce("description", '')), 'B') ||
    setweight(to_tsvector('english', coalesce("content", '')), 'C') ||
    setweight(to_tsvector('english', coalesce("sourceName", '')), 'D')
  ) STORED;

CREATE INDEX "news_articles_search_vector_idx"
  ON "news_articles" USING GIN ("search_vector");

-- Trigram index on the title for fuzzy fallback ("bitcon" -> "bitcoin").
CREATE INDEX "news_articles_title_trgm_idx"
  ON "news_articles" USING GIN ("title" gin_trgm_ops);

-- Stories are searched by headline too (the "compare coverage" entry point).
ALTER TABLE "stories"
  ADD COLUMN "search_vector" tsvector
  GENERATED ALWAYS AS (
    setweight(to_tsvector('english', coalesce("title", '')), 'A') ||
    setweight(to_tsvector('english', coalesce("summary", '')), 'B')
  ) STORED;

CREATE INDEX "stories_search_vector_idx"
  ON "stories" USING GIN ("search_vector");

-- Note: no partial (WHERE status = 'PUBLISHED') indexes here on purpose. Prisma
-- cannot express partial indexes, so they would show up as permanent schema drift.
-- The composite indexes declared in schema.prisma -- ("status", "publishedAt" DESC)
-- and ("category", "importanceScore" DESC) -- already serve the feed queries, since
-- status is the leading column of the first and the planner has an exact-match
-- predicate for it.
